/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BandingkanRouteImport } from './routes/bandingkan'
import { Route as ChecklistRouteImport } from './routes/checklist'
import { Route as DpsRouteImport } from './routes/dps'
import { Route as HealerRouteImport } from './routes/healer'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BandingkanRoute = BandingkanRouteImport.update({
  id: '/bandingkan',
  path: '/bandingkan',
  getParentRoute: () => rootRouteImport,
} as any)
const ChecklistRoute = ChecklistRouteImport.update({
  id: '/checklist',
  path: '/checklist',
  getParentRoute: () => rootRouteImport,
} as any)
const DpsRoute = DpsRouteImport.update({
  id: '/dps',
  path: '/dps',
  getParentRoute: () => rootRouteImport,
} as any)
const HealerRoute = HealerRouteImport.update({
  id: '/healer',
  path: '/healer',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bandingkan': typeof BandingkanRoute
  '/checklist': typeof ChecklistRoute
  '/dps': typeof DpsRoute
  '/healer': typeof HealerRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bandingkan': typeof BandingkanRoute
  '/checklist': typeof ChecklistRoute
  '/dps': typeof DpsRoute
  '/healer': typeof HealerRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bandingkan': typeof BandingkanRoute
  '/checklist': typeof ChecklistRoute
  '/dps': typeof DpsRoute
  '/healer': typeof HealerRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bandingkan' | '/checklist' | '/dps' | '/healer'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bandingkan' | '/checklist' | '/dps' | '/healer'
  id: '__root__' | '/' | '/bandingkan' | '/checklist' | '/dps' | '/healer'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BandingkanRoute: typeof BandingkanRoute
  ChecklistRoute: typeof ChecklistRoute
  DpsRoute: typeof DpsRoute
  HealerRoute: typeof HealerRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bandingkan': {
      id: '/bandingkan'
      path: '/bandingkan'
      fullPath: '/bandingkan'
      preLoaderRoute: typeof BandingkanRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checklist': {
      id: '/checklist'
      path: '/checklist'
      fullPath: '/checklist'
      preLoaderRoute: typeof ChecklistRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dps': {
      id: '/dps'
      path: '/dps'
      fullPath: '/dps'
      preLoaderRoute: typeof DpsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/healer': {
      id: '/healer'
      path: '/healer'
      fullPath: '/healer'
      preLoaderRoute: typeof HealerRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BandingkanRoute: BandingkanRoute,
  ChecklistRoute: ChecklistRoute,
  DpsRoute: DpsRoute,
  HealerRoute: HealerRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
